name: Deploy Function Code to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip function code
      run: zip -r function.zip .

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Upload function code to GCS
      run: gsutil cp function.zip gs://${{ secrets.GCS_BUCKET_NAME }}/function.zip
