name: Instance template creation
on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.saKey }}      

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
    - name: "Use gcloud CLI"
      run: |
          ls -al          
          gcloud info
          gcloud auth list 
          chmod +x ./scripts/gcloud.sh
          ./scripts/gcloud.sh
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        SA_KEY: ${{ secrets.SA_KEY }}
        REGION: ${{ secrets.REGION }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        ENC_KEY: ${{ secrets.ENC_KEY }}
        SA_EMAIL: ${{ secrets.SA_EMAIL }}
        FALLBACK_CREATE_INSTANCE_TEMPLATE: ${{ secrets.FALLBACK_CREATE_INSTANCE_TEMPLATE }}
        FALLBACK_UPDATE_MANAGED_INSTANCE_GROUP: ${{ secrets.FALLBACK_UPDATE_MANAGED_INSTANCE_GROUP }}


