name: Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
      

    steps:
      - uses: actions/checkout@v4
      - name: Install MySQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or another version of Node.js you're using

      - name: Install dependencies
        run: |
          ls -al
          npm ci
      
      - name: Setup Prisma
        run: npx prisma generate      
      
      - name: Setup Databse Env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |          
          npx prisma db push

      - name: Set up Prisma
        run: npx prisma generate

      - name: Set up Database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma db push

      - name: Run integration tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm test
